# Form implementation generated from reading ui file 'main_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_main = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.verticalLayout.addWidget(self.tabWidget_main)
        self.horizontalLayout_foorter = QtWidgets.QHBoxLayout()
        self.horizontalLayout_foorter.setObjectName("horizontalLayout_foorter")
        self.label_author = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_author.setObjectName("label_author")
        self.horizontalLayout_foorter.addWidget(self.label_author)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_foorter.addItem(spacerItem)
        self.label_version = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_version.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_foorter.addWidget(self.label_version)
        self.verticalLayout.addLayout(self.horizontalLayout_foorter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_author.setText(_translate("MainWindow", "MrYapikZ"))
        self.label_version.setText(_translate("MainWindow", "TextLabel"))
